import "./globals.css";
import Sidebar from "./Sidebar";

export const metadata = {
  title: "Bytecraft Ranking System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="  w-screen overflow-x-hidden">
        <div className="flex w-full">
          <Sidebar></Sidebar>
          <div className="w-full">
            <div className="h-10"></div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
